export enum CATEGORIES_ACTION_TYPES {
    SET_CATEGORIES="categories/SET_CATEGORIES",
    FETCH_CATEGORY_START= "category/FETCH_CATEGORY_START",
    FETCH_CATEGORY_SUCCESS = "category/FETCH_CATEGORY_SUCCESS",
    FETCH_CATEGORY_FAILED= "category/FETCH_CATEGORY_FAILED"
}
